-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 13:46:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema music_stream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music_stream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_stream` DEFAULT CHARACTER SET utf8 ;
USE `music_stream` ;

-- -----------------------------------------------------
-- Table `music_stream`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_stream`.`canciones` (
  `id_cancion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `año` INT NULL,
  `artista` VARCHAR(100) NULL,
  `reproducciones` INT NULL,
  `genero` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cancion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_stream`.`artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_stream`.`artistas` (
  `id_artista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `biografia` LONGTEXT NULL,
  `popularidad` INT NULL,
  `similares` LONGTEXT NULL,
  PRIMARY KEY (`id_artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_stream`.`canciones_artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_stream`.`canciones_artistas` (
  `canciones_id_cancion` INT NOT NULL,
  `artistas_id_artista` INT NOT NULL,
  PRIMARY KEY (`canciones_id_cancion`, `artistas_id_artista`),
  INDEX `fk_canciones_has_artistas_artistas1_idx` (`artistas_id_artista` ASC) VISIBLE,
  INDEX `fk_canciones_has_artistas_canciones_idx` (`canciones_id_cancion` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_has_artistas_canciones`
    FOREIGN KEY (`canciones_id_cancion`)
    REFERENCES `music_stream`.`canciones` (`id_cancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canciones_has_artistas_artistas1`
    FOREIGN KEY (`artistas_id_artista`)
    REFERENCES `music_stream`.`artistas` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
